name: Build and deploy to EKS

on:
  push:
    paths:
      - 'Backend/**'
      - 'frontend/**'
    branches: [ release ]

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0' # default is latest stable
        id: install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
      - name: Path Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'frontend/**'
      



  api-deploy:
    needs: common-steps
    name: Build and Deploy API
    #if: needs.common-steps.outputs.filter.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        run: echo "Backend Filter Value: ${{ needs.common-steps.outputs.filter.backend }}"
      

  ui-deploy:
    needs: common-steps
    
    name: Build and Deploy Frontend
    #if: needs.common-steps.outputs.filter.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output
        run: echo "Frontend Filter Value: ${{ needs.common-steps.outputs.filter.frontend }}"

      
